name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install deps
        run: npm ci
      - name: Run tests
        run: npm test --silent
      - name: Start static server
        run: node ./tools/static-server.js &
      - name: Run headless scenario
        run: node ./tools/run_scenario.js
      - name: Upload experiment artifacts
        uses: actions/upload-artifact@v4
        with:
          name: experiment-results
          path: experiments/results/**
